## This workflow will trigger another workflow in another repository within your organization
## Currently the workflow resides in https://github.com/lcchua/github-actions-reusable-workflow/blob/main/.github/reusable-workflow.yaml

name: Call a reusable workflow

## Change the branches and on strategies to suit your needs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch

## When calling a reusable workflow, make sure you follow the format:
## <github account name>/<github repo name>/.github/workflows/<workflow name>@<branch name>

jobs:
  call-workflow:
    uses: lcchua/github-actions-reusable-workflow/.github/workflows/reusable-workflow.yaml@main
    with:
      user-name: "david"
      address: "singapore"
      age: "23"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
